name: mad_demo_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# ... (version and environment sections remain the same)
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.3.0 
  
  # ⭐️ ADDED FIREBASE STORAGE AND UPDATED AUTH/FIRESTORE VERSIONS FOR CONSISTENCY
  firebase_storage: ^12.4.10 # Required for image uploads
  
  image_picker: ^1.1.2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# ... (The rest of the file remains the same)
flutter:
  uses-material-design: true