// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXBGrP5g98rleYCXdyzdw5cckNSuRwN8',
    appId: '1:253392969727:web:869a82f3f3eb0fd52551ca',
    messagingSenderId: '253392969727',
    projectId: 'my-app-8798',
    authDomain: 'my-app-8798.firebaseapp.com',
    storageBucket: 'my-app-8798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2dBnhIdtA8wGPNJQDWETxnC6QjUWiUQ',
    appId: '1:253392969727:android:fa813aa743c988612551ca',
    messagingSenderId: '253392969727',
    projectId: 'my-app-8798',
    storageBucket: 'my-app-8798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpIBktZdRftIXjzwcT4GejcFn_kxvXw4',
    appId: '1:253392969727:ios:ac39b3c1a57066d52551ca',
    messagingSenderId: '253392969727',
    projectId: 'my-app-8798',
    storageBucket: 'my-app-8798.firebasestorage.app',
    iosBundleId: 'com.example.madProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgpIBktZdRftIXjzwcT4GejcFn_kxvXw4',
    appId: '1:253392969727:ios:ac39b3c1a57066d52551ca',
    messagingSenderId: '253392969727',
    projectId: 'my-app-8798',
    storageBucket: 'my-app-8798.firebasestorage.app',
    iosBundleId: 'com.example.madProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFXBGrP5g98rleYCXdyzdw5cckNSuRwN8',
    appId: '1:253392969727:web:9d8d8ea7ae5ecfea2551ca',
    messagingSenderId: '253392969727',
    projectId: 'my-app-8798',
    authDomain: 'my-app-8798.firebaseapp.com',
    storageBucket: 'my-app-8798.firebasestorage.app',
  );
}
